# Generated by Django 4.2.5 on 2023-09-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Activity link')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now=True)),
                ('certificate_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('certificate_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('certificate', 'Certificate')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=350, verbose_name='Module name')),
                ('order', models.IntegerField(default=1, verbose_name='Order of the module')),
            ],
        ),
    ]
