# Generated by Django 4.2.5 on 2023-11-12 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Institution or University name')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('XX', 'Other')], max_length=2, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=280, verbose_name='City')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Name')),
                ('username', models.CharField(blank=True, max_length=280, null=True, verbose_name='Wikimedia username')),
            ],
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Course name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('course_type', models.CharField(choices=[('in_person', 'In person'), ('hybrid', 'Hybrid'), ('online', 'Online')], default=None, max_length=10, verbose_name='Course type')),
                ('number_students', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of students or participants')),
                ('institution', models.ManyToManyField(related_name='education_program_institution', to='education_program.institution', verbose_name='Institution')),
                ('professor', models.ManyToManyField(related_name='education_program_professor', to='education_program.professor', verbose_name='Professor')),
            ],
        ),
    ]
